global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alert.rules/mysqld-alerts.rules"
  - "/etc/prometheus/alert.rules/node-alerts.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: mysql # To get metrics about the mysql exporter’s targets
    params:
    # Not required. Will match value to child in config file. Default value is `client`.
    #auth_module: [client.servers]
    static_configs:
    - targets:
      # All mysql hostnames or unix sockets to monitor.
      - 138.197.68.80:3306
      - unix:///run/mysqld/mysqld.sock
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      # The mysqld_exporter host:port
      replacement: 174.138.52.52:9104